# Generated by Django 3.1 on 2021-02-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCID', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
