# Generated by Django 3.1 on 2021-02-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCID', '0002_npc_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
