# Generated by Django 3.1 on 2020-10-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCID', '0002_auto_20200906_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPC_school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('contents', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='npc',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
