# Generated by Django 3.1 on 2020-10-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCID', '0003_auto_20201002_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc_bookmark',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
