# Generated by Django 3.1 on 2021-02-17 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NCID', '0003_auto_20210217_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npc',
            old_name='photo',
            new_name='images',
        ),
    ]
