# Generated by Django 3.1 on 2021-03-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCID', '0004_auto_20210217_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPC_university',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100)),
                ('contents', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
