# Generated by Django 3.1 on 2021-03-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCID', '0006_auto_20210324_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
